name: Node.js CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['14']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install packages
        run: yarn
      - name: Test
        run: yarn test
